[tool.poetry]
name = "rss-gpt"
version = "0.1.0"
description = ""
authors = ["timsu27 <omg80827@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
feedparser = "6.0.11"
configparser = "7.1.0"
openai = "1.56.2"
jinja2 = "3.1.4"
beautifulsoup4 = "4.12.3"
httpx = "0.28.0"
requests = "2.32.3"
fake-useragent = "1.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
